[
{ id: 1,
       username: 'jack',
       roomname: 'lobby',
       text: 'bob was here',
       createdat: Sat May 10 2014 14:05:12 GMT-0700 (PDT) }
]




[ { dataValues:
     { id: 1,
       username: 'jack',
       roomname: 'lobby',
       text: 'bob was here',
       createdat: Sat May 10 2014 14:05:12 GMT-0700 (PDT) },
    _previousDataValues:
     { id: 1,
       username: 'jack',
       roomname: 'lobby',
       text: 'bob was here',
       createdat: Sat May 10 2014 14:05:12 GMT-0700 (PDT) },
    __options:
     { timestamps: false,
       createdAt: 'createdAt',
       updatedAt: 'updatedAt',
       deletedAt: 'deletedAt',
       instanceMethods: {},
       classMethods: {},
       validate: {},
       freezeTableName: false,
       underscored: false,
       syncOnAssociation: true,
       paranoid: false,
       whereCollection: null,
       schema: null,
       schemaDelimiter: '',
       language: 'en',
       defaultScope: null,
       scopes: null,
       hooks: [Object],
       omitNull: false,
       uniqueKeys: {},
       hasPrimaryKeys: true },
    options: { isNewRecord: false, isDirty: false, raw: true },
    hasPrimaryKeys: true,
    selectedValues:
     { id: 1,
       username: 'jack',
       roomname: 'lobby',
       text: 'bob was here',
       createdat: Sat May 10 2014 14:05:12 GMT-0700 (PDT) },
    __eagerlyLoadedAssociations: [],
    isNewRecord: false },
  { dataValues:
     { id: 2,
       username: 'jack',
       roomname: 'lobby',
       text: 'bob was here',
       createdat: Sat May 10 2014 16:17:14 GMT-0700 (PDT) },
    _previousDataValues:
     { id: 2,
       username: 'jack',
       roomname: 'lobby',
       text: 'bob was here',
       createdat: Sat May 10 2014 16:17:14 GMT-0700 (PDT) },
    __options:
     { timestamps: false,
       createdAt: 'createdAt',
       updatedAt: 'updatedAt',
       deletedAt: 'deletedAt',
       instanceMethods: {},
       classMethods: {},
       validate: {},
       freezeTableName: false,
       underscored: false,
       syncOnAssociation: true,
       paranoid: false,
       whereCollection: null,
       schema: null,
       schemaDelimiter: '',
       language: 'en',
       defaultScope: null,
       scopes: null,
       hooks: [Object],
       omitNull: false,
       uniqueKeys: {},
       hasPrimaryKeys: true },
    options: { isNewRecord: false, isDirty: false, raw: true },
    hasPrimaryKeys: true,
    selectedValues:
     { id: 2,
       username: 'jack',
       roomname: 'lobby',
       text: 'bob was here',
       createdat: Sat May 10 2014 16:17:14 GMT-0700 (PDT) },
    __eagerlyLoadedAssociations: [],
    isNewRecord: false }
]
